#!/usr/bin/env python3
"""Ping IndexNow with a site's real URLs, read from its own sitemap.

Why this exists: cycles were hand-typing URLs into a curl, and one of them
guessed `/team/tigers.html` when team pages are directories, so the ping went
to a 404. The sitemap is generated by build.py from the same list of pages it
just wrote, so reading it is the only way the ping cannot disagree with the
site.

Two things that are easy to get wrong and are handled here:

  - The `host` must be the custom domain. The github.io host returns a soft 202
    and does not serve the key file, so ownership never verifies.
  - `keyLocation` has to be the key file the build wrote at the site root.

Covers Bing, DuckDuckGo's sources, Yandex, Seznam, Naver. Google is separate
and uses Search Console.

Usage:  python scripts/indexnow.py            # both sites
        python scripts/indexnow.py dsr        # one site
"""

from __future__ import annotations

import json
import re
import sys
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from build import DSR, JOURNAL, Site  # noqa: E402

ENDPOINT = "https://api.indexnow.org/indexnow"
SITES = {"journal": JOURNAL, "dsr": DSR}


def urls_for(site: Site) -> list[str]:
    sitemap = (site.out / "sitemap.xml").read_text(encoding="utf-8")
    urls = re.findall(r"<loc>([^<]+)</loc>", sitemap)
    feed = f"{site.base_url}/feed.xml"
    if (site.out / "feed.xml").exists() and feed not in urls:
        urls.append(feed)
    return urls


def ping(site: Site) -> None:
    if not site.indexnow_key or not site.custom_domain:
        print(f"{site.key}: no key or no custom domain, skipped")
        return
    urls = urls_for(site)
    payload = {
        "host": site.custom_domain,
        "key": site.indexnow_key,
        "keyLocation": f"{site.base_url}/{site.indexnow_key}.txt",
        "urlList": urls,
    }
    req = urllib.request.Request(
        ENDPOINT,
        data=json.dumps(payload).encode(),
        headers={"Content-Type": "application/json; charset=utf-8"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            status = r.status
    except urllib.error.HTTPError as exc:      # a 4xx is a real answer, not a crash
        status = exc.code
    # 200 is accepted. 202 means "received, key not checked yet", which on this
    # project has always meant the host was wrong.
    print(f"{site.key}: {status} for {len(urls)} urls on {site.custom_domain}")
    if status != 200:
        print("  not a 200. Check that the key file is served on that host.")


if __name__ == "__main__":
    wanted = sys.argv[1:] or list(SITES)
    for key in wanted:
        if key not in SITES:
            sys.exit(f"unknown site {key!r}; choose from {', '.join(SITES)}")
        ping(SITES[key])
